### ISSUE TITLE
Incluir uma seção de Certificações para os Cards

### ISSUE THREAD

**Issue by andrebreves** [alura/techguide#104]
Sugiro ter uma seção para poder indicar certificações para um determinado Card.

**Comment by fabriciocarraro** [comment]
Oi @andrebreves. Acho que foge um pouco do escopo do TechGuide, porque a ideia é guiar a pessoa nos conceitos a serem aprendidos e mostrar pra ela conteúdos que vão ajudar nesse aprendizado. Ter Certificações é algo que está em um segundo momento. Obrigado pela sugestão de qualquer forma!

**Comment by andrebreves** [comment]
> porque a ideia é guiar a pessoa nos conceitos a serem aprendidos e mostrar pra ela conteúdos que vão ajudar nesse aprendizado

Entendo o posicionamento. Vale reforçar que certificados podem servir como um excelente guia para os estudos.
