### ISSUE TITLE
[ bug ] - Tech Guide Android

### ISSUE THREAD

**Issue by pgomes22** [alura/techguide#112]
Erro ao tentar baixar o tech guide de android.

![image](https://user-images.githubusercontent.com/84644758/212763197-7faabbdd-bb40-437a-ac3a-65ac56bca1f3.png)

**Comment by fabriciocarraro** [comment]
@omariosouto

**Comment by gferreir** [comment]
PR aberta: #113

**Comment by felipesuri** [comment]
Bug solved on #113! :+1:

The issue can be closed! @fabriciocarraro
