### ISSUE TITLE
Adicionar tag canonical nas páginas do Tech Guide

### ISSUE THREAD

**Issue by GabrielSBraz** [alura/techguide#127]
Olá, pessoal. Tudo bem? Podem me ajudar, por favor?

Existe uma pendência (grave) na [Home do Tech Guide](https://techguide.sh/): ao procurar no código-fonte da página não é encontrada a tag canonical. Por isso devemos fazer o seguinte:

1. Precisamos adicionar a tag canonical na [página inicial (a Home) do Tech Guide](https://techguide.sh/) para, com isso, sinalizar aos buscadores (em especifico o Google) que no caso de existirem URLs diferentes, mas que se referem ao mesmo tipo de conteúdo, ou seja, à mesma página, que ele deve considerar como a "original" aquela que está referenciada na tag canonical. Por isso é preciso adicionar ao código-fonte da página a seguinte linha:

`<link rel="canonical” href=”https://techguide.sh”/>
`

---

Um exemplo para entender melhor para que serve e qual a função dessa tag é o seguinte caso:

temos a seguinte página de influencer (com UTMs):

* https://techguide.sh/?utm_source=influenciadores&utm_medium=codigofontetv&utm_campaign=techguide

Ela se diferencia na sua URL da URL original da home (https://techguide.sh/), porém as duas são referentes à mesma página, ou seja, ao mesmo (idêntico) Conteúdo. Por conta dessa possibilidade de existir diferentes URLs para o mesmo Conteúdo se faz necessário indicarmos no código para o mecanismo de busca que:

* Não estamos produzindo conteúdo duplicado, que para o caso desse grupo de páginas iguais ele deve considerar como a página "original" aquela que está indicada na tag canonical e, com isso, também garantimos que no caso da indexação nos Resultados de Buscas também apenas aparecerá esta mesma indicada.

**Descreva o valor agregado:**

Evitar a penalização do Google para o caso de entendimento de Conteúdo duplicado, facilitar a indexação da página correta.

**_Essa pendência foi identificada através do Google Search Console e vale a pena verificar se a tag canonical está presente nas demais páginas do Site do Tech Guide._**

Desde já agradeço.

**Comment by fabriciocarraro** [comment]
@omariosouto Pode dar uma olhada?

**Comment by GabrielSBraz** [comment]
Pessoal, qual o retorno aqui, por favor?

**Comment by imteekay** [comment]
@GabrielSBraz Abri um PR pra adicionar o canonical URL pra cada página: https://github.com/alura/techguide/pull/152
