### ISSUE TITLE
Poder ler yamls de outros repositorios e desenhar o T de pessoas/empresas

### ISSUE THREAD

**Issue by peas** [alura/techguide#13]
Uma pessoa pode criar seu proprio guide.yaml com yamls de cards e, através de alguma url (techguide.sh/external/_user_/_repository_), gerar o T que foi definido ali

Assim outras pessoas podem compatilhar seu proprio T de como imagina uma determinada carreira. Isso também pode ser usado para empresas mostrarem o que consideram importante para vagas de emprego, assim como outras escolas e faculdades poderão linkar para seus conteúdos em seus Ts.

**Comment by omariosouto** [comment]
Essa inclusive é a que eu estou trabalhando atualmente, em breve compartilho algumas descobertas aqui na thread

**Comment by rodriguesmatpc** [comment]
Eu posso desenvolver um guide de Git e GitHub por exemplo e vincular o meu repositório com esse tal de YAMLs? E issi iria começar a eu mesmo desenhar o meu próprio Dev em T? 
Não sei se entendi direito.
