### ISSUE TITLE
Criação para Carreira em DevOps

### ISSUE THREAD

**Issue by nilsonvieira** [alura/techguide#14]

**Comment by cirino** [comment]
Vim aqui só para apoiar

**Comment by Engcompaulo** [comment]
Opa, como posso contribuir  ?

**Comment by nilsonvieira** [comment]
Bom, eu criei a issue mas ainda não criei a base para tal, pensei em me basear na carreira Devops que foi montada no [roadmap.sh](https://roadmap.sh/devops) e tenho inclusive um artigo falando sobre essa base no meu [medium](https://nilsonrsvieira.medium.com/quero-me-tornar-um-devops-o-que-fazer-2f2d52d3ec9e). Mas infelizmente estou meio sem tempo de implementar, mas acho que já é um primeiro passo. :)

**Comment by fabriciocarraro** [comment]
@nilsonvieira @cirino @Engcompaulo acabou de ser lançado este guia! Se tiverem sugestões, podem fazer PR's que nós analisamos :)

Abraços!
