### ISSUE TITLE
Existe um erro de digitação na parte de CSS - fundamentos

### ISSUE THREAD

**Issue by livehass** [alura/techguide#159]
### está escrito "Aprender box-sizinh" deveria ser "Aprender box-sizing"
![1](https://github.com/alura/techguide/assets/9482519/d2cbdf39-f0a4-48de-a2f2-69b414244502)

#### não sei se é o local correto para reportar esse tipo de erro, então de antemão peço desculpas caso esteja incorreto.

**Comment by fabriciocarraro** [comment]
@livehass Corrigido! Obrigado!
