### ISSUE TITLE
[bug] Criando seu próprio guia

### ISSUE THREAD

**Issue by estevancosta** [alura/techguide#161]
a [funcionalidade de criação de um novo guia](https://github.com/alura/techguide/blob/main/docs/br/criando-seu-guide.md) está  retornando erro 500.

Para reproduzir pode ser utilizada a url de exemplo https://techguide.sh/pt-BR/my?url=https://github.com/omariosouto/omariosouto/blob/main/techguide-v1.json

**Comment by fabriciocarraro** [comment]
@omariosouto

**Comment by fabriciocarraro** [comment]
@estevancosta corrigido!
