### ISSUE TITLE
Efeito hover no menu principal

### ISSUE THREAD

**Issue by carolsvntos** [alura/techguide#20]
Na página principal temos uma seleção de guias de carreiras, mas parece que o `transition` do hover não está funcionando bem.

**Comment by omariosouto** [comment]
Esse aqui é um desafio legal, hover com gradiente n é uma ciência exata: https://stackoverflow.com/questions/6542212/use-css3-transitions-with-gradient-backgrounds

Deixo de dica pra quem for fazer:
- Pra esse caso criar um styled components 
- Tentar aplicar a tecnica aqui de cima
- Manda o PR com um gif demonstrando como ficou rodando na sua maquina pra gente conseguir ver :D

**Comment by sucodelarangela** [comment]
PR #31 enviado.
