### ISSUE TITLE
Efeito sanfona no FAQ mais suave

### ISSUE THREAD

**Issue by carolsvntos** [alura/techguide#21]
Nas páginas do projeto temos uma área destinada para perguntas frequentes. Atualmente, você clica e ele abre de maneira um pouco dura. Seria bem legal se tivesse uma transição um pouco mais suave, mostrando o elemento da resposta crescendo ou diminuindo.

**Comment by marco-beduschi** [comment]
### Proposta de Solução
Olá! Quero pegar essa issue, e pensei em usar uma solução só usando HTML & CSS, fazendo uma transição de max-height, exemplo:

```js
<Box
// ...
transition: `max-height 0.5s ${isOpen ? "ease-in-out" : "cubic-bezier(0, 1, 0, 1)"}`,
maxHeight: isOpen ? "1000px" : 0,
// ...
```
#### Desktop
![accordion-desktop](https://user-images.githubusercontent.com/8469440/190246891-91dcd780-1774-4142-a300-b71501aae771.gif)


#### Mobile
![accordion-mobile](https://user-images.githubusercontent.com/8469440/190246907-b7656a32-f464-4f87-8877-97f805f658a2.gif)

#### Vantagens
- Zero Javascript
- Poucas linhas de código
- Funciona até no IE10 🙏 

#### Desvantagens
- com CSS não dá pra saber o tamanho do conteúdo do acordão antes de abri-lo, então é necessário um `overflow: scroll` pro caso que o texto seja maior que o `max-height`
- pra deixar essa animação acessível pra leitores de tela precisamos usar `aria-expanded`, `aria-hidden` e ` aria-controls`.

**Comment by felipesuri** [comment]
Olá @marco-beduschi acredito que não precise pedir autorzação para fazer alguma alteração. Basta fazer o seu fork, abrir um merge request e aguardar a revisão ou aprovação.

**Comment by marco-beduschi** [comment]
ah, beleza então. 😄
