### ISSUE TITLE
Links dos conteúdos recomendados da FIAP quebrados?

### ISSUE THREAD

**Issue by MuriloChianfa** [alura/techguide#237]
Boa noite pessoal, estava vendo o vídeo "Guia de Carreira: Cibersegurança" e decidí dar uma olhada nos conteúdos do guia,
porém ao tentar abrir o curso da FIAP em qualquer sessão:

![image](https://github.com/alura/techguide/assets/60560085/6798331f-f841-4a5e-b36b-7803ea3795ea)

Esta retornando este erro no link

![image](https://github.com/alura/techguide/assets/60560085/75b72251-1443-4464-aa45-7051d39421dc)

É possível que tenham removido o curso do site?

**Comment by fabriciocarraro** [comment]
@MuriloChianfa Corrigido! Obrigado :)
