### ISSUE TITLE
Opção de marcar concluído

### ISSUE THREAD

**Issue by christiandmelo** [alura/techguide#242]
Seria legal se tivéssemos uma opção de marcar que já concluímos um bloco do guia.

**Comment by fabriciocarraro** [comment]
Olá @christiandmelo. Para isso, teríamos que ter uma conta com usuário e senha associada a cada usuário, o que já foge atualmente do nosso escopo. Porém, você tem a opção de exportar o guia e colocálo em um Trello, Notion ou Google Docs, e assim poder gerar essas marcações. Abraços!
