### ISSUE TITLE
API própia da Alura para portfolio

### ISSUE THREAD

**Issue by AshileySabah** [alura/techguide#252]
Quero fazer um portfolio e seria bom se tivesse uma api da Alura para listar minhas formações e cursos terminados e baixar os pdfs dos certificados. Tem algo já existente?

**Comment by fabriciocarraro** [comment]
@AshileySabah existe uma API beta, mas não é perfeita: https://suporte.alura.com.br/support/solutions/articles/72000565226-api-do-dashboard-para-alunos-e-alunas
