### ISSUE TITLE
Animação subindo a página ao clicar em "Selecionar minha carreira!"

### ISSUE THREAD

**Issue by TaylorNAlbarnaz** [alura/techguide#29]
No momento a página simplesmente pula para o topo imediatamente, seria legal se após o clique tivesse uma animação da tela subindo até o topo

**Comment by cirino** [comment]
Up

**Comment by marco-beduschi** [comment]
Dá pra fazer essa animação substituindo o `<Link />` por um `<Button />` e usando a [scroll API](https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll), exemplo: `window.scroll(top: 0, behavior: 'smooth')`

**Comment by omariosouto** [comment]
Agora temos! Valeu pela sugestão :D
