### ISSUE TITLE
[bug] Ícones no footer bugados ao utilizar Dark Reader

### ISSUE THREAD

**Issue by felipe-heredia** [alura/techguide#34]
Utilizando extensões que deixam a tela no modo dark, os ícones do footer somem.

![Screenshot 2022-09-14 at 19-03-24 Tech Guide guias do Profissional em T](https://user-images.githubusercontent.com/50281523/190271186-53eb225d-2036-4ecc-870b-42d98c743fff.png)

**Comment by imteekay** [comment]
Essa issue já está consertada, certo?

**Comment by angelacaldas** [comment]
Resolvido!
