### ISSUE TITLE
Criação de carreira PHP

### ISSUE THREAD

**Issue by brunomoraisti** [alura/techguide#35]
ROADMAP

[How Internet & Websites works]
[Browser/Server request flow, HTTP Protocol, Status codes]
[Basics of HTML/CSS]
[Basics of Javascript]
[Introduction to Databases]
[Version Control System (Git & Github)]
[Getting Familiar with PHP: Syntax, functions, dates, JSON, File System, CURL, etc...]
[Understanding Composer]
[PHP beginner projects]
[Object Oriented PHP]
[Build Projects]
[Build custom MVC Framework]
[What is API]
[Learn Existing Framework]
[Learn JavaScript]
[Basics of JavaScript Frameworks]
[Build Projects with existing frameworks]
[Get Familiar with Terminal]
[Editors/IDEs]
[Docker]
[Design Patterns]

**Comment by fabriciocarraro** [comment]
Olá Bruno,

Já temos uma carreira de PHP! :)

Segue o link: https://techguide.sh/pt-BR/path/php/
