### ISSUE TITLE
[bug] Link do vídeo "Marco Bruno: O que é Json e como criar um objeto" incorreto

### ISSUE THREAD

**Issue by ielison** [alura/techguide#38]
Em **JavaScript - Fundamentos**, presente trilha de _**Front-End**_, o link correto para o vídeo "_Marco Bruno: O que é Json e como criar um objeto_" é https://www.youtube.com/watch?v=oCY5YEEjlwE.

**Comment by fabriciocarraro** [comment]
Corrigido! Valeu, ielison!
