### ISSUE TITLE
[bug] Link de video errado

### ISSUE THREAD

**Issue by rafaelswitek** [alura/techguide#56]
O link do video PoliCast: Symfony 5 - Criando seu primeiro projeto está levando para o video API REST com Symfony 6 | Primeiros Passos e Setup Projeto

**Comment by carolsvntos** [comment]
Oi @rafaelswitek tudo bom?
Pode nos informar onde se encontra esse link errado, por gentileza?

**Comment by fabriciocarraro** [comment]
Corrigido!
