### ISSUE TITLE
Scrollbar aparecendo brevemente ao abrir/fechar elementos do FAQ

### ISSUE THREAD

**Issue by sucodelarangela** [alura/techguide#59]
Ao clicar nos elementos do FAQ, aparece brevemente à direita um overflow-y no ato de abertura/fechamento do conteúdo textual.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/86853033/194594644-981ec541-83a3-4d68-9b75-d06d36f96963.gif)

**Comment by omariosouto** [comment]
Valeu pela issue, to fechando pq foi resolvido :D
