### ISSUE TITLE
Artigo com link possivelmente errado

### ISSUE THREAD

**Issue by JoaoAugustoMV** [alura/techguide#69]
No **mapa de estudo C#**, no nível do 2 de profundidade no campo **ASP.NET CORE**, um dos tópicos diz:
- ASP.NET Core: dicas úteis para o dia a dia de um Desenvolvedor - Parte 1

Mas está este link abaixo:
- https://guih2127.medium.com/um-pouco-sobre-estruturas-de-dados-em-c-e4371fe651d8

PS: Este link está no tópico "Um pouco sobre estruturas de dados em c#, no nível de profundidade 1 no campo C# - Coleções

**Comment by fabriciocarraro** [comment]
Obrigado, João! Corrigido!

**Comment by JoaoAugustoMV** [comment]
Eu que agradeço por esse projeto!
