### ISSUE TITLE
Guia ReactJS com mesmas Habilidades em Infraestrutura e Back-end e UX e Design

### ISSUE THREAD

**Issue by alex0liveira** [alura/techguide#76]
Ao acessar o guia para [**Front-end ReactJS**](https://techguide.sh/pt-BR/path/react/), ao clicar no botão **Baixar este guia**, os arquivos react.md, [pt-BR](https://github.com/alura/techguide/blob/main/_data/downloadFiles/pt_BR/react.md) e [en-US](https://github.com/alura/techguide/blob/main/_data/downloadFiles/en_US/react.md), possuem as mesmas informações nas seções _Habilidade Auxiliar: Infrastructure and Back-end_ e _Habilidade Auxiliar: UX and Design_.

**Comment by fabriciocarraro** [comment]
O mesmo para a palavra "Nível"

**Comment by omariosouto** [comment]
@alex0liveira foi resolvido! Obrigado por reportar
