### ISSUE TITLE
"Download guide" with the titles in PT

### ISSUE THREAD

**Issue by fabriciocarraro** [alura/techguide#86]
Ao clicar em Download Guide da página em inglês, ele está vindo com os títulos em português (Nível, Habilidade auxiliar, etc). Exemplo: https://github.com/alura/techguide/blob/main/_data/downloadFiles/EN_US/react.md

**Comment by fabriciocarraro** [comment]
@omariosouto tem como corrigir? Imagino que vai ter que pegar do arquivo locale.

**Comment by imteekay** [comment]
@fabriciocarraro Criei um PR (https://github.com/alura/techguide/pull/151) para corrigir esse erro.
